### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by danfinlay** [pconstr/irf#1]
I tried installing fresh with both node 0.8.8 and node 0.10.0, and they both install-failing errors:

``````
 node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config --cflags libsparsehash' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:416:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System Darwin 11.4.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/danfinlay/Projects/node_modules/irf
gyp ERR! node -v v0.8.8
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok 
npm ERR! irf@0.1.4 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the irf@0.1.4 install script.
npm ERR! This is most likely a problem with the irf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls irf
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "irf"
npm ERR! cwd /Users/danfinlay/Projects/
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/danfinlay/Projects/npm-debug.log
npm ERR! not ok code 0```
``````

**Comment by pconstr** [comment]
flyswatter, irf requires http://goog-sparsehash.sourceforge.net/. Do you have it on your system?
I did not package it into irf so google sparse hash needs to be installed before running `npm install irf`
On OS X I usually install google sparse hash with http://mxcl.github.com/homebrew/ :
`brew install google-sparsehash`

**Comment by danfinlay** [comment]
That seems to have done it, thanks!  Homebrew worked great as usual.  If only it were on all systems, you could add `scripts{ "preinstall": 'echo "brew install google-sparsehash"'` to the package.json  There was one other problem too, the package.json was restricting node to 0.9.0, though 0.10.0 came out last week or so, so I tested it, removed the restrictions, and pushed you that with a new version number so you can push it straight to npm.
